[package]
edition.workspace = true
license.workspace = true
name = "whisply-cloud-tasks"
version.workspace = true

[lib]
name = "whisply_cloud_tasks"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
whisply-http-client = { workspace = true }
whisply-cloud-tasks-client = { workspace = true }
# TODO: whisply-cloud-tasks-mock-client should be in dev-dependencies.
whisply-cloud-tasks-mock-client = { workspace = true }
whisply-core = { workspace = true }
whisply-git-utils = { workspace = true }
whisply-login = { path = "../login" }
whisply-model-provider = { workspace = true }
whisply-tui = { workspace = true }
whisply-utils-cli = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
http = { workspace = true }
owo-colors = { workspace = true, features = ["supports-colors"] }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
supports-color = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
pretty_assertions = { workspace = true }
