//! Whisply-owned runtime contracts shared by the direct Codex-derived fork.
//!
//! This crate intentionally contains product contracts rather than an adapter
//! around user-provided provider configuration. Native execution, credentials,
//! and server authority remain behind their respective typed owners.

mod account;
mod app_server_config;
mod brand;
mod broker;
mod catalog;
mod diagnostics;
mod directory;
mod home;
mod permissions;
mod provenance;
mod runtime_descriptor_sealing;
mod skill_roots;
#[cfg(feature = "test-support")]
mod test_catalog;
#[cfg(feature = "test-support")]
mod test_gateway;
mod tool_envelope;
mod tools;

pub use account::AccountProjectionError;
pub use account::CONTEXTUAL_ACTION_CONTRACT_VERSION;
pub use account::ConnectorAccess;
pub use account::ConnectorDisclosureAccessBehavior;
pub use account::ConnectorProvider;
pub use account::ContextualConnectionStatus;
pub use account::ContextualConnectionSummary;
pub use account::ContextualConnectionUsage;
pub use account::ContextualConnectionsRetention;
pub use account::ContextualConnectionsSnapshot;
pub use account::ContextualConnectorAccountFamily;
pub use account::ContextualConnectorAuthorizationDisclosure;
pub use account::ContextualConnectorAuthorizationProfiles;
pub use account::ContextualConnectorAvailability;
pub use account::ContextualConnectorCapability;
pub use account::ContextualConnectorCatalogEntry;
pub use account::ContextualConnectorDisclosure;
pub use account::ContextualConnectorGrant;
pub use account::ContextualConnectorProduct;
pub use account::ContextualUsageMetering;
pub use account::ContextualUsageSnapshot;
pub use account::ContextualUsageTokenTotals;
pub use account::ContextualUsageTokenWindows;
pub use account::ContextualUsageWindow;
pub use account::USAGE_METERING_BASIS;
pub use account::USAGE_METERING_CONTRACT_VERSION;
pub use account::UsageWindowCategory;
pub use account::UsageWindowKind;
pub use app_server_config::APPROVAL_CONTRACT_FEATURE;
pub use app_server_config::APPROVAL_CONTRACT_KEY;
pub use app_server_config::AppServerContractError;
pub use app_server_config::ApprovalContract;
pub use app_server_config::ApprovalContractMode;
pub use app_server_config::DIRECTORY_CONTRACT_FEATURE;
pub use app_server_config::DIRECTORY_CONTRACT_KEY;
pub use app_server_config::DirectoryContract;
pub use app_server_config::DirectoryContractMode;
pub use app_server_config::WhisplyThreadContracts;
pub use brand::DEFAULT_HOME_DIR;
pub use brand::EXECUTABLE_NAME;
pub use brand::GATEWAY_AUTH_FD_ENV;
pub use brand::GATEWAY_ENDPOINT_FD_ENV;
pub use brand::HOME_ENV;
pub use brand::NATIVE_BROKER_CAPABILITY_FD_ENV;
pub use brand::NATIVE_BROKER_SOCKET_ENV;
pub use brand::PRODUCT_NAME;
pub use brand::RELEASE_MANIFEST_SHA256_ENV;
pub use brand::WHISPLY_PROVIDER_ID;
pub use brand::release_manifest_sha256_from_environment;
pub use brand::user_agent;
pub use broker::BrokerError;
pub use broker::BrokerErrorCode;
pub use broker::BrokerLoginBegin;
pub use broker::BrokerLoginStatus;
pub use broker::BrokerOperation;
pub use broker::BrokerResponseMetadata;
pub use broker::GatewayDescriptorSnapshot;
pub use broker::HostControlsAudioAssistMode;
pub use broker::HostControlsBuiltinCapability;
pub use broker::HostControlsCommand;
pub use broker::HostControlsComputerUseRoute;
pub use broker::HostControlsInteractiveAction;
pub use broker::HostControlsPatch;
pub use broker::HostControlsPermissionMode;
pub use broker::HostControlsThreadDirectory;
pub use broker::ManagedGatewayClient;
pub use broker::ManagedGatewayError;
pub use broker::ManagedGatewaySessionAvailability;
#[cfg(feature = "test-support")]
pub use broker::ManagedGatewayTestLaunch;
pub use broker::NativeBrokerClient;
pub use broker::managed_gateway_client_from_environment;
pub use catalog::CATALOG_KEY_SET_RESOURCE_FILENAME;
pub use catalog::CATALOG_KEY_SET_SCHEMA_VERSION;
pub use catalog::CatalogEnvelope;
pub use catalog::CatalogError;
pub use catalog::CatalogModel;
pub use catalog::CatalogVerificationKey;
pub use catalog::CatalogVerificationKeySet;
pub use catalog::CatalogVerifier;
pub use catalog::MODEL_CATALOG_SCHEMA_VERSION;
pub use catalog::MODEL_CATALOG_SIGNATURE_VERSION;
pub use catalog::ModelAvailability;
pub use catalog::ModelCapabilities;
pub use catalog::ModelCatalog;
pub use catalog::ModelId;
pub use catalog::SUPPORTED_CATALOG_PROFILES;
pub use catalog::SUPPORTED_CATALOG_REASONING_EFFORTS;
pub use catalog::SubscriptionAvailability;
pub use catalog::catalog_key_set_path_for_runtime_binary;
pub use catalog::load_catalog_key_set_for_current_runtime;
pub use catalog::load_catalog_key_set_for_runtime_binary;
pub use diagnostics::ContractReplayRequest;
pub use diagnostics::DEFAULT_FIXTURE_SESSION_TTL_MS;
pub use diagnostics::DIAGNOSTIC_PROTOCOL_SCHEMA_VERSION;
pub use diagnostics::DiagnosticIpcFrame;
pub use diagnostics::DiagnosticLane;
pub use diagnostics::DiagnosticLaunchManifest;
pub use diagnostics::DiagnosticSecurityError;
pub use diagnostics::DiagnosticSessionAuthenticator;
pub use diagnostics::DiagnosticTerminalStatus;
pub use diagnostics::FixtureAppearance;
pub use diagnostics::FixtureArtifactManifest;
pub use diagnostics::FixtureCapturePoint;
pub use diagnostics::FixtureScenario;
pub use diagnostics::FixtureValidationError;
pub use diagnostics::ForceUiRequest;
pub use diagnostics::MAX_DIAGNOSTIC_FRAME_BYTES;
pub use diagnostics::MAX_FIXTURE_SESSION_TTL_MS;
pub use diagnostics::OwnerOnlyTemporaryRoot;
pub use diagnostics::PRESENTATION_FIXTURE_MARKER;
pub use diagnostics::RealIntegrationAccount;
pub use diagnostics::RealIntegrationRequest;
pub use diagnostics::decode_bounded_diagnostic_frame;
#[cfg(unix)]
pub use diagnostics::read_one_time_diagnostic_capability;
#[cfg(unix)]
pub use diagnostics::validate_diagnostic_socket_peer;
pub use diagnostics::validate_owner_only_diagnostic_socket;
pub use diagnostics::validate_owner_only_temporary_root;
pub use diagnostics::validate_socket_path_inside_root;
pub use directory::DirectorySelection;
pub use directory::DirectorySelectionError;
pub use home::AccountKey;
pub use home::AccountRuntimeHome;
pub use home::RuntimeHomeError;
pub use home::ensure_private_runtime_directory;
pub use permissions::ApprovalPacket;
pub use permissions::AutoReviewDecision;
pub use permissions::AutoReviewReason;
pub use permissions::PermissionMode;
pub use permissions::resolve_auto_review;
pub use provenance::RuntimeLineage;
pub use provenance::UPSTREAM_COMMIT;
pub use provenance::UPSTREAM_TAG;
pub use provenance::WHISPLY_RUNTIME_VERSION;
pub use runtime_descriptor_sealing::RuntimeDescriptorSealingError;
pub use runtime_descriptor_sealing::seal_inherited_runtime_descriptors;
pub use skill_roots::SkillRoot;
pub use skill_roots::SkillRootKind;
pub use skill_roots::SkillRoots;
#[cfg(feature = "test-support")]
pub use test_catalog::test_catalog_key_set;
#[cfg(feature = "test-support")]
pub use test_catalog::test_signed_catalog_envelope;
pub use tool_envelope::MAX_TOOL_ENVELOPE_LIFETIME_MS;
pub use tool_envelope::TOOL_EXECUTION_ENVELOPE_SCHEMA_VERSION;
pub use tool_envelope::ToolEnvelopeError;
pub use tool_envelope::ToolExecutionEnvelope;
pub use tool_envelope::TrustedEnvelopeVerifier;
pub use tool_envelope::WhisplyExecutionEnvelope;
pub use tool_envelope::WhisplyToolAppServerCancelAcknowledgement;
pub use tool_envelope::WhisplyToolAppServerCancelRequest;
pub use tool_envelope::WhisplyToolAppServerExecuteRequest;
pub use tool_envelope::WhisplyToolAppServerRequestMethod;
pub use tool_envelope::WhisplyToolLeasePhase;
pub use tool_envelope::WhisplyToolModelCall;
pub use tool_envelope::WhisplyToolPolicyDecision;
pub use tool_envelope::WhisplyToolPolicyInput;
pub use tool_envelope::WhisplyToolProgress;
pub use tool_envelope::WhisplyToolResult;
pub use tool_envelope::WhisplyToolTerminalStatus;
pub use tool_envelope::compile_policy_for;
pub use tool_envelope::validate_envelope_static;
pub use tool_envelope::validate_execute_request;
pub use tool_envelope::validate_progress;
pub use tool_envelope::validate_result;
pub use tools::ActionClass;
pub use tools::TOOL_REGISTRY_SCHEMA_VERSION;
pub use tools::ToolAvailability;
pub use tools::ToolDescriptor;
pub use tools::ToolOwner;
pub use tools::ToolRegistry;
pub use tools::ToolRegistryError;
pub use tools::ToolRegistrySnapshot;
pub use tools::first_party_tool_registry;
