// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal execution states. Setup and confirmation are suspension points,
 * not successful authority escalation.
 */
export type WhisplyToolTerminalStatus = "succeeded" | "failed" | "cancelled" | "setup_required" | "confirmation_required" | "unavailable";
