// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress delivered through the normal typed item/event path.
 */
export type WhisplyToolProgress = { executionID: string, label: string, fraction: number | null, };
