// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An independently-produced policy decision. Aggregation must only make a
 * decision stricter; a call may not use this wire object to relax policy.
 */
export type WhisplyToolPolicyDecision = { "kind": "allowed" } | { "kind": "setup_required", route: string, } | { "kind": "confirmation_required" } | { "kind": "denied", reason: string, } | { "kind": "unavailable", reason: string, };
