// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyExecutionEnvelope } from "./WhisplyExecutionEnvelope";

/**
 * Trusted cancellation request for `whisply/tool/cancel`.
 */
export type WhisplyToolAppServerCancelRequest = { executionID: string, envelope: WhisplyExecutionEnvelope, };
