// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WhisplyToolTerminalStatus } from "./WhisplyToolTerminalStatus";

/**
 * Terminal result delivered through the normal typed item/event path.
 */
export type WhisplyToolResult = { executionID: string, status: WhisplyToolTerminalStatus, content: JsonValue | null, safeSummary: string, setupRoute: string | null, receiptID: string | null, };
