// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed cancellation acknowledgement. It never contains handler secrets or
 * authority data.
 */
export type WhisplyToolAppServerCancelAcknowledgement = { executionID: string, accepted: boolean, };
