[package]
edition.workspace = true
license.workspace = true
name = "whisply-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
whisply-protocol = { workspace = true }
whisply-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
