//! Whisply-owned runtime contracts shared by the direct Codex-derived fork.
//!
//! This crate intentionally contains product contracts rather than an adapter
//! around user-provided provider configuration. Native execution, credentials,
//! and server authority remain behind their respective typed owners.

mod account;
mod account_usage_presentation;
mod app_server_config;
mod brand;
mod broker;
mod catalog;
mod child_env;
mod conversation_compaction;
mod diagnostic_fixture_event;
#[cfg(test)]
#[path = "diagnostic_fixture_event_tests.rs"]
mod diagnostic_fixture_event_tests;
mod diagnostic_fixture_execution;
#[cfg(test)]
#[path = "diagnostic_fixture_execution_tests.rs"]
mod diagnostic_fixture_execution_tests;
mod diagnostic_fixture_replay;
#[cfg(test)]
#[path = "diagnostic_fixture_replay_tests.rs"]
mod diagnostic_fixture_replay_tests;
mod diagnostic_fixture_selectors;
#[cfg(test)]
#[path = "diagnostic_fixture_selectors_tests.rs"]
mod diagnostic_fixture_selectors_tests;
mod diagnostic_fixture_thread;
#[cfg(test)]
#[path = "diagnostic_fixture_thread_tests.rs"]
mod diagnostic_fixture_thread_tests;
mod diagnostic_fixture_timeline;
#[cfg(test)]
#[path = "diagnostic_fixture_timeline_tests.rs"]
mod diagnostic_fixture_timeline_tests;
mod diagnostics;
#[cfg(test)]
mod diagnostics_tests;
mod directory;
mod home;
mod local_storage;
mod log_redaction;
mod permissions;
mod personalization_memory;
mod prompt_composition;
mod provenance;
mod runtime_descriptor_sealing;
mod skill_roots;
mod terminal_status;
#[cfg(feature = "test-support")]
mod test_catalog;
#[cfg(feature = "test-support")]
mod test_gateway;
mod tool_envelope;
mod tools;
mod untrusted_content;

pub use account::AccountProjectionError;
pub use account::CONTEXTUAL_ACTION_CONTRACT_VERSION;
pub use account::ConnectorAccess;
pub use account::ConnectorDisclosureAccessBehavior;
pub use account::ConnectorProvider;
pub use account::ContextualConnectionStatus;
pub use account::ContextualConnectionSummary;
pub use account::ContextualConnectionUsage;
pub use account::ContextualConnectionsRetention;
pub use account::ContextualConnectionsSnapshot;
pub use account::ContextualConnectorAccountFamily;
pub use account::ContextualConnectorAuthorizationDisclosure;
pub use account::ContextualConnectorAuthorizationProfiles;
pub use account::ContextualConnectorAvailability;
pub use account::ContextualConnectorCapability;
pub use account::ContextualConnectorCatalogEntry;
pub use account::ContextualConnectorDisclosure;
pub use account::ContextualConnectorGrant;
pub use account::ContextualConnectorProduct;
pub use account::ContextualUsageMetering;
pub use account::ContextualUsageSnapshot;
pub use account::ContextualUsageTokenTotals;
pub use account::ContextualUsageTokenWindows;
pub use account::ContextualUsageWindow;
pub use account::USAGE_METERING_BASIS;
pub use account::USAGE_METERING_CONTRACT_VERSION;
pub use account::UsageWindowCategory;
pub use account::UsageWindowKind;
pub use account_usage_presentation::ACCOUNT_USAGE_SIGNED_OUT;
pub use account_usage_presentation::ACCOUNT_USAGE_UNAVAILABLE;
pub use account_usage_presentation::account_usage_used_fraction;
pub use account_usage_presentation::account_usage_window_name;
pub use account_usage_presentation::format_account_usage;
pub use account_usage_presentation::read_account_usage;
pub use app_server_config::APPROVAL_CONTRACT_FEATURE;
pub use app_server_config::APPROVAL_CONTRACT_KEY;
pub use app_server_config::AppServerContractError;
pub use app_server_config::ApprovalContract;
pub use app_server_config::ApprovalContractMode;
pub use app_server_config::DIRECTORY_CONTRACT_FEATURE;
pub use app_server_config::DIRECTORY_CONTRACT_KEY;
pub use app_server_config::DirectoryContract;
pub use app_server_config::DirectoryContractMode;
pub use app_server_config::WhisplyThreadContracts;
pub use brand::DEFAULT_HOME_DIR;
pub use brand::EXECUTABLE_NAME;
pub use brand::GATEWAY_AUTH_FD_ENV;
pub use brand::GATEWAY_ENDPOINT_FD_ENV;
pub use brand::HOME_ENV;
pub use brand::NATIVE_BROKER_CAPABILITY_FD_ENV;
pub use brand::NATIVE_BROKER_SOCKET_ENV;
pub use brand::PRODUCT_NAME;
pub use brand::RELEASE_MANIFEST_SHA256_ENV;
pub use brand::RUNTIME_BROKER_CONTROL_ONLY_ENV;
pub use brand::WHISPLY_PROVIDER_ID;
pub use brand::release_manifest_sha256_from_environment;
pub use brand::user_agent;
pub use broker::BrokerError;
pub use broker::BrokerErrorCode;
pub use broker::BrokerLoginBegin;
pub use broker::BrokerLoginStatus;
pub use broker::BrokerOperation;
pub use broker::BrokerResponseMetadata;
pub use broker::GatewayDescriptorSnapshot;
pub use broker::HostControlsAudioAssistMode;
pub use broker::HostControlsBuiltinCapability;
pub use broker::HostControlsCommand;
pub use broker::HostControlsComputerUseRoute;
pub use broker::HostControlsInteractiveAction;
pub use broker::HostControlsPatch;
pub use broker::HostControlsPermissionMode;
pub use broker::HostControlsThreadDirectory;
pub use broker::ManagedGatewayClient;
pub use broker::ManagedGatewayError;
pub use broker::ManagedGatewaySessionAvailability;
#[cfg(feature = "test-support")]
pub use broker::ManagedGatewayTestLaunch;
pub use broker::NativeBrokerClient;
pub use broker::managed_gateway_client_from_environment;
pub use catalog::CATALOG_KEY_SET_RESOURCE_FILENAME;
pub use catalog::CATALOG_KEY_SET_SCHEMA_VERSION;
pub use catalog::CatalogEnvelope;
pub use catalog::CatalogError;
pub use catalog::CatalogModel;
pub use catalog::CatalogVerificationKey;
pub use catalog::CatalogVerificationKeySet;
pub use catalog::CatalogVerifier;
pub use catalog::MODEL_CATALOG_SCHEMA_VERSION;
pub use catalog::MODEL_CATALOG_SIGNATURE_VERSION;
pub use catalog::ModelAvailability;
pub use catalog::ModelCapabilities;
pub use catalog::ModelCatalog;
pub use catalog::ModelId;
pub use catalog::SUPPORTED_CATALOG_PROFILES;
pub use catalog::SUPPORTED_CATALOG_REASONING_EFFORTS;
pub use catalog::SubscriptionAvailability;
pub use catalog::catalog_key_set_path_for_runtime_binary;
pub use catalog::load_catalog_key_set_for_current_runtime;
pub use catalog::load_catalog_key_set_for_runtime_binary;
pub use child_env::RESERVED_ENV_PREFIX;
pub use child_env::RUNTIME_AUTHORITY_ENV;
pub use child_env::env_var_is_reserved;
pub use child_env::reserved_names_in;
pub use child_env::withhold_reserved_environment;
pub use child_env::withhold_runtime_authority;
pub use conversation_compaction::CONVERSATION_COMPACTION_CONTRACT_VERSION;
pub use conversation_compaction::CompactionBudget;
pub use conversation_compaction::CompactionLimitScope;
pub use conversation_compaction::CompactionMechanism;
pub use conversation_compaction::CompactionObservation;
pub use conversation_compaction::CompactionOutcome;
pub use conversation_compaction::CompactionRecord;
pub use conversation_compaction::CompactionTriggerKind;
pub use conversation_compaction::ConversationCompactionLog;
pub use conversation_compaction::ConversationCompactionStatus;
pub use conversation_compaction::MAX_COMPACTION_RECORDS;
pub use conversation_compaction::summary_digest;
pub use diagnostic_fixture_event::DIAGNOSTIC_FIXTURE_EVENT_PROTOCOL;
pub use diagnostic_fixture_event::DIAGNOSTIC_FIXTURE_EVENT_SCHEMA_VERSION;
pub use diagnostic_fixture_event::DiagnosticFixtureAdapterContract;
pub use diagnostic_fixture_event::DiagnosticFixtureAdapterKind;
pub use diagnostic_fixture_event::DiagnosticFixtureAdapterMode;
pub use diagnostic_fixture_event::DiagnosticFixtureEventCheckpoint;
pub use diagnostic_fixture_event::DiagnosticFixtureEventEnvelope;
pub use diagnostic_fixture_event::DiagnosticFixtureEventError;
pub use diagnostic_fixture_event::DiagnosticFixtureEventKind;
pub use diagnostic_fixture_event::DiagnosticFixtureEventStream;
pub use diagnostic_fixture_event::MAX_DIAGNOSTIC_FIXTURE_EVENTS;
pub use diagnostic_fixture_event::build_diagnostic_fixture_event_stream;
pub use diagnostic_fixture_execution::DIAGNOSTIC_FIXTURE_EXECUTION_PROTOCOL;
pub use diagnostic_fixture_execution::DIAGNOSTIC_FIXTURE_EXECUTION_SCHEMA_VERSION;
pub use diagnostic_fixture_execution::DiagnosticFixtureExecution;
pub use diagnostic_fixture_execution::DiagnosticFixtureExecutionError;
pub use diagnostic_fixture_execution::build_diagnostic_fixture_execution;
pub use diagnostic_fixture_replay::DIAGNOSTIC_FIXTURE_REPLAY_PROTOCOL;
pub use diagnostic_fixture_replay::DIAGNOSTIC_FIXTURE_REPLAY_SCHEMA_VERSION;
pub use diagnostic_fixture_replay::DiagnosticFixtureReplayControl;
pub use diagnostic_fixture_replay::DiagnosticFixtureReplayError;
pub use diagnostic_fixture_replay::DiagnosticFixtureReplaySpeed;
pub use diagnostic_fixture_replay::DiagnosticFixtureReplayState;
pub use diagnostic_fixture_replay::MAX_DIAGNOSTIC_FIXTURE_REPLAY_CONTROLS;
pub use diagnostic_fixture_replay::build_diagnostic_fixture_replay;
pub use diagnostic_fixture_replay::initial_diagnostic_fixture_replay;
pub use diagnostic_fixture_replay::reduce_diagnostic_fixture_replay;
pub use diagnostic_fixture_selectors::DIAGNOSTIC_FIXTURE_SELECTOR_PROTOCOL;
pub use diagnostic_fixture_selectors::DIAGNOSTIC_FIXTURE_SELECTOR_SCHEMA_VERSION;
pub use diagnostic_fixture_selectors::DiagnosticFixtureAccountSelector;
pub use diagnostic_fixture_selectors::DiagnosticFixtureModelSelector;
pub use diagnostic_fixture_selectors::DiagnosticFixtureProfileSelector;
pub use diagnostic_fixture_selectors::DiagnosticFixtureSelectorError;
pub use diagnostic_fixture_selectors::DiagnosticFixtureSelectors;
pub use diagnostic_fixture_selectors::DiagnosticFixtureToolSelector;
pub use diagnostic_fixture_selectors::build_diagnostic_fixture_selectors;
pub use diagnostic_fixture_thread::DIAGNOSTIC_FIXTURE_THREAD_PROTOCOL;
pub use diagnostic_fixture_thread::DIAGNOSTIC_FIXTURE_THREAD_SCHEMA_VERSION;
pub use diagnostic_fixture_thread::DIAGNOSTIC_FIXTURE_THREAD_STEP_INTERVAL_MS;
pub use diagnostic_fixture_thread::DiagnosticFixtureThreadPlan;
pub use diagnostic_fixture_thread::DiagnosticFixtureThreadPlanError;
pub use diagnostic_fixture_thread::DiagnosticScheduledOutcome;
pub use diagnostic_fixture_thread::DiagnosticScheduledOutcomeKind;
pub use diagnostic_fixture_thread::DiagnosticVirtualClock;
pub use diagnostic_fixture_thread::MAX_DIAGNOSTIC_FIXTURE_THREAD_OUTCOMES;
pub use diagnostic_fixture_thread::build_diagnostic_fixture_thread_plan;
pub use diagnostic_fixture_timeline::DIAGNOSTIC_FIXTURE_THREAD_TIMELINE_PROTOCOL;
pub use diagnostic_fixture_timeline::DIAGNOSTIC_FIXTURE_THREAD_TIMELINE_SCHEMA_VERSION;
pub use diagnostic_fixture_timeline::DiagnosticFixtureThreadLifecycle;
pub use diagnostic_fixture_timeline::DiagnosticFixtureThreadProjection;
pub use diagnostic_fixture_timeline::DiagnosticFixtureThreadTimeline;
pub use diagnostic_fixture_timeline::build_diagnostic_fixture_thread_timeline;
pub use diagnostic_fixture_timeline::project_diagnostic_fixture_thread_plan;
pub use diagnostics::ContractReplayRequest;
pub use diagnostics::DEFAULT_FIXTURE_SESSION_TTL_MS;
pub use diagnostics::DIAGNOSTIC_PROTOCOL_SCHEMA_VERSION;
pub use diagnostics::DIAGNOSTIC_SCENARIO_REGISTRY_PROTOCOL;
pub use diagnostics::DIAGNOSTIC_SCENARIO_REGISTRY_SCHEMA_VERSION;
pub use diagnostics::DIAGNOSTIC_SCENARIO_RUNNER_VERSION;
pub use diagnostics::DiagnosticCommercialBoundary;
pub use diagnostics::DiagnosticIpcFrame;
pub use diagnostics::DiagnosticLane;
pub use diagnostics::DiagnosticLaunchManifest;
pub use diagnostics::DiagnosticScenario;
pub use diagnostics::DiagnosticScenarioAuthority;
pub use diagnostics::DiagnosticScenarioDefaults;
pub use diagnostics::DiagnosticScenarioFixture;
pub use diagnostics::DiagnosticScenarioRegistry;
pub use diagnostics::DiagnosticScenarioRegistryError;
pub use diagnostics::DiagnosticSecurityError;
pub use diagnostics::DiagnosticSessionAuthenticator;
pub use diagnostics::DiagnosticTerminalStatus;
pub use diagnostics::FixtureAppearance;
pub use diagnostics::FixtureArtifactManifest;
pub use diagnostics::FixtureCapturePoint;
pub use diagnostics::FixtureDisplay;
pub use diagnostics::FixtureFontScale;
pub use diagnostics::FixtureLayoutDirection;
pub use diagnostics::FixturePresentation;
pub use diagnostics::FixtureScenario;
pub use diagnostics::FixtureTheme;
pub use diagnostics::FixtureValidationError;
pub use diagnostics::ForceUiRequest;
pub use diagnostics::MAX_DIAGNOSTIC_FRAME_BYTES;
pub use diagnostics::MAX_FIXTURE_SESSION_TTL_MS;
pub use diagnostics::OwnerOnlyTemporaryRoot;
pub use diagnostics::PRESENTATION_FIXTURE_MARKER;
pub use diagnostics::RealIntegrationAccount;
pub use diagnostics::RealIntegrationRequest;
pub use diagnostics::decode_bounded_diagnostic_frame;
pub use diagnostics::fixture_capture_for_replay;
pub use diagnostics::parse_diagnostic_scenario_registry;
#[cfg(unix)]
pub use diagnostics::read_one_time_diagnostic_capability;
#[cfg(unix)]
pub use diagnostics::validate_diagnostic_socket_peer;
pub use diagnostics::validate_owner_only_diagnostic_socket;
pub use diagnostics::validate_owner_only_temporary_root;
pub use diagnostics::validate_socket_path_inside_root;
pub use directory::CliWorkingRoot;
pub use directory::DirectorySelection;
pub use directory::DirectorySelectionError;
pub use directory::NO_DIRECTORY_WORKSPACE_DIR_NAME;
pub use directory::no_directory_working_root;
pub use directory::resolve_cli_working_root;
pub use home::AccountKey;
pub use home::AccountRuntimeHome;
pub use home::RuntimeHomeError;
pub use home::ensure_private_runtime_directory;
pub use local_storage::ExportOutcome;
pub use local_storage::MAX_LOG_FILE_BYTES;
pub use local_storage::RemovalOutcome;
pub use local_storage::StorageCategory;
pub use local_storage::StorageCategoryId;
pub use local_storage::StorageError;
pub use local_storage::StorageInventory;
pub use local_storage::enforce_log_retention;
pub use local_storage::export as export_local_storage;
pub use local_storage::inventory as local_storage_inventory;
pub use local_storage::remove_category as remove_local_storage_category;
pub use local_storage::resolve_home as resolve_local_storage_home;
pub use log_redaction::REDACTED;
pub use log_redaction::RedactedLogWriter;
pub use permissions::ApprovalPacket;
pub use permissions::AutoReviewDecision;
pub use permissions::AutoReviewReason;
pub use permissions::FULL_ACCESS_WARNING;
pub use permissions::PermissionMode;
pub use permissions::resolve_auto_review;
pub use personalization_memory::AttributedMemory;
pub use personalization_memory::MAX_PERSONALIZATION_BYTES;
pub use personalization_memory::MAX_PERSONALIZATION_ITEMS;
pub use personalization_memory::MemoryAttribution;
pub use personalization_memory::MemoryControls;
pub use personalization_memory::PERSONALIZATION_ORIGIN_ID;
pub use personalization_memory::PersonalizationError;
pub use personalization_memory::personalization_contribution;
pub use prompt_composition::ComposedPrompt;
pub use prompt_composition::LayerSource;
pub use prompt_composition::MAX_PROMPT_CONTRIBUTIONS;
pub use prompt_composition::MAX_PROMPT_LAYER_BYTES;
pub use prompt_composition::ModeCompositionInput;
pub use prompt_composition::NATIVE_DISCOVERY_ORIGINS;
pub use prompt_composition::PROMPT_COMPOSITION_CONTRACT_VERSION;
pub use prompt_composition::PromptCompositionDiagnostics;
pub use prompt_composition::PromptCompositionError;
pub use prompt_composition::PromptContribution;
pub use prompt_composition::PromptLayerDigest;
pub use prompt_composition::PromptLayerKind;
pub use prompt_composition::PromptProfile;
pub use prompt_composition::ToolAuthority;
pub use prompt_composition::WHISPLY_GENERAL_ASSISTANT_IDENTITY;
pub use prompt_composition::WorkspaceIntent;
pub use provenance::RuntimeLineage;
pub use provenance::UPSTREAM_COMMIT;
pub use provenance::UPSTREAM_TAG;
pub use provenance::WHISPLY_RUNTIME_VERSION;
pub use runtime_descriptor_sealing::RuntimeDescriptorSealingError;
pub use runtime_descriptor_sealing::seal_inherited_runtime_descriptors;
pub use skill_roots::SkillRoot;
pub use skill_roots::SkillRootKind;
pub use skill_roots::SkillRoots;
pub use terminal_status::WhisplyTerminalStatus;
#[cfg(feature = "test-support")]
pub use test_catalog::test_catalog_key_set;
#[cfg(feature = "test-support")]
pub use test_catalog::test_signed_catalog_envelope;
pub use tool_envelope::MAX_TOOL_ENVELOPE_LIFETIME_MS;
pub use tool_envelope::TOOL_EXECUTION_ENVELOPE_SCHEMA_VERSION;
pub use tool_envelope::ToolEnvelopeError;
pub use tool_envelope::ToolExecutionEnvelope;
pub use tool_envelope::TrustedEnvelopeVerifier;
pub use tool_envelope::WhisplyExecutionEnvelope;
pub use tool_envelope::WhisplyToolAppServerCancelAcknowledgement;
pub use tool_envelope::WhisplyToolAppServerCancelRequest;
pub use tool_envelope::WhisplyToolAppServerExecuteRequest;
pub use tool_envelope::WhisplyToolAppServerRequestMethod;
pub use tool_envelope::WhisplyToolLeasePhase;
pub use tool_envelope::WhisplyToolModelCall;
pub use tool_envelope::WhisplyToolPolicyDecision;
pub use tool_envelope::WhisplyToolPolicyInput;
pub use tool_envelope::WhisplyToolProgress;
pub use tool_envelope::WhisplyToolResult;
pub use tool_envelope::WhisplyToolTerminalStatus;
pub use tool_envelope::compile_policy_for;
pub use tool_envelope::describe_setup_route;
pub use tool_envelope::validate_envelope_static;
pub use tool_envelope::validate_execute_request;
pub use tool_envelope::validate_progress;
pub use tool_envelope::validate_result;
pub use tools::ActionClass;
pub use tools::TOOL_REGISTRY_SCHEMA_VERSION;
pub use tools::ToolAvailability;
pub use tools::ToolDescriptor;
pub use tools::ToolOwner;
pub use tools::ToolRegistry;
pub use tools::ToolRegistryArtifactAvailability;
pub use tools::ToolRegistryArtifactDescriptor;
pub use tools::ToolRegistryArtifactOwner;
pub use tools::ToolRegistryArtifactSnapshot;
pub use tools::ToolRegistryError;
pub use tools::ToolRegistrySnapshot;
pub use tools::first_party_tool_registry;
pub use untrusted_content::UntrustedChannel;
pub use whisply_utils_string::redact_log_line;
