[package]
name = "core_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
base64 = { workspace = true }
whisply-arg0 = { workspace = true }
whisply-config = { workspace = true }
whisply-core = { workspace = true }
whisply-extension-api = { workspace = true }
whisply-exec-server = { workspace = true }
whisply-home = { workspace = true }
whisply-features = { workspace = true }
whisply-hooks = { workspace = true }
whisply-login = { workspace = true }
whisply-model-provider-info = { workspace = true }
whisply-models-manager = { workspace = true }
whisply-protocol = { workspace = true }
codex-whisply = { workspace = true, features = ["test-support"] }
whisply-utils-absolute-path = { workspace = true }
whisply-utils-cargo-bin = { workspace = true }
whisply-utils-path-uri = { workspace = true }
ctor = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
regex-lite = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["net", "test-util", "time"] }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
wiremock = { workspace = true }
shlex = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
whisply-http-client = { workspace = true }
pretty_assertions = { workspace = true }
