// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyPatchApprovalParams } from "./ApplyPatchApprovalParams";
import type { ExecCommandApprovalParams } from "./ExecCommandApprovalParams";
import type { RequestId } from "./RequestId";
import type { AttestationGenerateParams } from "./v2/AttestationGenerateParams";
import type { ChatgptAuthTokensRefreshParams } from "./v2/ChatgptAuthTokensRefreshParams";
import type { CommandExecutionRequestApprovalParams } from "./v2/CommandExecutionRequestApprovalParams";
import type { DynamicToolCallParams } from "./v2/DynamicToolCallParams";
import type { FileChangeRequestApprovalParams } from "./v2/FileChangeRequestApprovalParams";
import type { McpServerElicitationRequestParams } from "./v2/McpServerElicitationRequestParams";
import type { PermissionsRequestApprovalParams } from "./v2/PermissionsRequestApprovalParams";
import type { ToolRequestUserInputParams } from "./v2/ToolRequestUserInputParams";
import type { WhisplyToolAdmittedCancelRequest } from "./v2/WhisplyToolAdmittedCancelRequest";
import type { WhisplyToolAdmittedExecuteRequest } from "./v2/WhisplyToolAdmittedExecuteRequest";
import type { WhisplyToolAppServerCancelRequest } from "./v2/WhisplyToolAppServerCancelRequest";
import type { WhisplyToolAppServerExecuteRequest } from "./v2/WhisplyToolAppServerExecuteRequest";

/**
 * Request initiated from the server and sent to the client.
 */
export type ServerRequest ={ "method": "item/commandExecution/requestApproval", id: RequestId, params: CommandExecutionRequestApprovalParams, } | { "method": "item/fileChange/requestApproval", id: RequestId, params: FileChangeRequestApprovalParams, } | { "method": "item/tool/requestUserInput", id: RequestId, params: ToolRequestUserInputParams, } | { "method": "mcpServer/elicitation/request", id: RequestId, params: McpServerElicitationRequestParams, } | { "method": "item/permissions/requestApproval", id: RequestId, params: PermissionsRequestApprovalParams, } | { "method": "item/tool/call", id: RequestId, params: DynamicToolCallParams, } | { "method": "whisply/tool/execute", id: RequestId, params: WhisplyToolAppServerExecuteRequest, } | { "method": "whisply/tool/cancel", id: RequestId, params: WhisplyToolAppServerCancelRequest, } | { "method": "whisply/tool/admittedExecute", id: RequestId, params: WhisplyToolAdmittedExecuteRequest, } | { "method": "whisply/tool/admittedCancel", id: RequestId, params: WhisplyToolAdmittedCancelRequest, } | { "method": "account/chatgptAuthTokens/refresh", id: RequestId, params: ChatgptAuthTokensRefreshParams, } | { "method": "attestation/generate", id: RequestId, params: AttestationGenerateParams, } | { "method": "applyPatchApproval", id: RequestId, params: ApplyPatchApprovalParams, } | { "method": "execCommandApproval", id: RequestId, params: ExecCommandApprovalParams, };
