// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bounded transfer frame for a product conversation that a new runtime
 * thread has never seen. This moves stored data; it never starts model work.
 */
export type WhisplyHistoryRecoveryFrame = { archiveId: string, offset: bigint, dataBase64: string, finalByteCount?: bigint | null, finalSha256?: string | null, };
