// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One declared MCP server, written out as the process it would become.
 *
 * Environment variables are named but never valued: the point is to show what
 * the server is reaching for, and printing a secret to disclose that it will
 * be shared defeats the disclosure.
 */
export type PluginMcpLaunchSummary = { serverName: string, launch: string, };
