// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookEventName } from "./HookEventName";
import type { HookHandlerType } from "./HookHandlerType";

export type PluginHookSummary = { key: string, eventName: HookEventName,
/**
 * Command handlers run a shell command unprompted; prompt and agent
 * handlers do not execute anything on the user's machine.
 */
handlerType: HookHandlerType,
/**
 * The command line this hook will run, so installing is a decision about
 * something the user has seen rather than about a hook count.
 */
command: string | null,
/**
 * Which occurrences of the event the hook is scoped to. `None` means every
 * occurrence, which is the wider exposure of the two.
 */
matcher: string | null, };
