// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { AppSummary } from "./AppSummary";
import type { AppTemplateSummary } from "./AppTemplateSummary";
import type { PluginHookSummary } from "./PluginHookSummary";
import type { PluginMcpLaunchSummary } from "./PluginMcpLaunchSummary";
import type { PluginSummary } from "./PluginSummary";
import type { ScheduledTaskSummary } from "./ScheduledTaskSummary";
import type { SkillSummary } from "./SkillSummary";

export type PluginDetail = { marketplaceName: string, marketplacePath: AbsolutePathBuf | null, summary: PluginSummary, shareUrl: string | null, description: string | null, skills: Array<SkillSummary>, hooks: Array<PluginHookSummary>, apps: Array<AppSummary>, appTemplates: Array<AppTemplateSummary>, mcpServers: Array<string>,
/**
 * What each of those servers would actually start, in the same order.
 *
 * The names alone say a plugin contributes a server. They do not say it
 * runs `sh -c` on something it downloaded, and that is the part a person
 * is deciding about before installing.
 */
mcpServerLaunches: Array<PluginMcpLaunchSummary>,
/**
 * What installing this signs up for after today: how a new version
 * arrives, and whether it runs when it does.
 */
updateBehavior: string | null,
/**
 * Host environment variables this plugin's MCP servers declare they will
 * read. Shown before install so sharing them is a decision rather than a
 * discovery.
 */
hostEnvVars: Array<string>,
/**
 * Reserved names the plugin asked for and will not receive. Kept separate
 * from the forwarded list because a plugin reaching for Whisply's own
 * namespace is worth seeing, not worth hiding just because it failed.
 */
refusedHostEnvVars: Array<string>, scheduledTasks: Array<ScheduledTaskSummary> | null, };
