// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyHistoryRecoveryFrame } from "../WhisplyHistoryRecoveryFrame";
import type { JsonValue } from "../serde_json/JsonValue";

export type ThreadInjectItemsParams = { threadId: string,
/**
 * Raw Responses API items to append to the thread's model-visible history.
 */
items: Array<JsonValue>,
/**
 * Whisply's bounded, idle-only stored-history recovery transfer. When
 * present, `items` must be empty; only the next normal user turn hydrates
 * the durable archive using normal model/Usage/compaction authority.
 */
whisplyHistoryRecovery?: WhisplyHistoryRecoveryFrame | null, };
