// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyHistoryRecoveryReceipt } from "../WhisplyHistoryRecoveryReceipt";

export type ThreadInjectItemsResponse = { whisplyHistoryRecovery?: WhisplyHistoryRecoveryReceipt | null, };
