// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { JsonValue } from "../serde_json/JsonValue";
import type { AdditionalContextEntry } from "./AdditionalContextEntry";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { UserInput } from "./UserInput";

export type TurnStartParams = {threadId: string, /**
 * Optional native-broker Exam turn reference. Transport-only: it is not
 * model context, durable history, or authority without its exact broker
 * registration. Omission keeps ordinary admission unchanged.
 */
whisplyExamTurnReference?: string | null, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Optional client-provided context fragments keyed by an opaque source identifier.
 *
 * Stable in the Whisply fork (TDR-006). Whisply continues conversations
 * the runtime has never seen — ones that predate it, and ones whose
 * rollout was pruned — and this is how the prior conversation is handed
 * over once, attributed to its source, and recorded in thread history.
 * A client cannot opt into the whole experimental surface just to say
 * what the model is being continued from.
 */
additionalContext?: { [key in string]?: AdditionalContextEntry } | null, /**
 * Override the working directory for this turn and subsequent turns.
 */
cwd?: string | null, /**
 * Override the approval policy for this turn and subsequent turns.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this turn and
 * subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, /**
 * Override the sandbox policy for this turn and subsequent turns.
 */
sandboxPolicy?: SandboxPolicy | null, /**
 * Override the model for this turn and subsequent turns.
 */
model?: string | null, /**
 * Override the service tier for this turn and subsequent turns.
 */
serviceTier?: string | null | null, /**
 * Override the reasoning effort for this turn and subsequent turns.
 */
effort?: ReasoningEffort | null, /**
 * Override the reasoning summary for this turn and subsequent turns.
 */
summary?: ReasoningSummary | null, /**
 * Override the personality for this turn and subsequent turns.
 */
personality?: Personality | null, /**
 * Optional JSON Schema used to constrain the final assistant message for
 * this turn.
 */
outputSchema?: JsonValue | null};
