// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who asked for a conversation to be shortened.
 */
export type WhisplyCompactionTrigger = "automatic" | "requested";
