// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyCompactionMechanism } from "./WhisplyCompactionMechanism";
import type { WhisplyCompactionOutcome } from "./WhisplyCompactionOutcome";
import type { WhisplyCompactionTrigger } from "./WhisplyCompactionTrigger";

/**
 * One shortening that happened to a conversation.
 *
 * Deliberately a digest rather than the summary: the summary is the person's
 * conversation in compressed form, and a diagnostic surface that carried it
 * would be a way to read a chat without opening it. The digest is enough to
 * show that a resumed thread holds the summary compaction wrote.
 */
export type WhisplyCompactionRecord = { sequence: number, trigger: WhisplyCompactionTrigger, mechanism: WhisplyCompactionMechanism, outcome: WhisplyCompactionOutcome, activeContextTokensBefore: bigint, activeContextTokensAfter: bigint, summaryTokens: bigint | null, summarySha256: string | null,
/**
 * Whether the shortened history reached the thread's stored record. A
 * shortening that was not written down is read back long on the next
 * resume.
 */
persisted: boolean, recordedAtUnixMs: bigint, };
