// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyCompactionBudget } from "./WhisplyCompactionBudget";
import type { WhisplyCompactionRecord } from "./WhisplyCompactionRecord";

export type WhisplyCompactionReadResponse = { contractVersion: number,
/**
 * Absent until the thread has run a turn, because until then nothing has
 * measured the window.
 */
budget: WhisplyCompactionBudget | null, compactionCount: number,
/**
 * The most recent shortenings, oldest first.
 */
records: Array<WhisplyCompactionRecord>, };
