// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Idempotent acknowledgement for a native admission release request.
 */
export type WhisplyToolAdmissionFinishResponse = { released: boolean, };
