// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyPromptLayerSource } from "./WhisplyPromptLayerSource";

/**
 * One layer's revision-safe fingerprint.
 *
 * Deliberately a digest rather than the contributed text: a client can prove
 * which prompt revision ran, and compare it across surfaces and releases,
 * without the composed instructions leaving the runtime.
 */
export type WhisplyPromptLayerDigest = { layerId: string, precedence: number, source: WhisplyPromptLayerSource, originId: string, byteLength: bigint, textSha256: string, };
