// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side contributed a prompt layer.
 */
export type WhisplyPromptLayerSource = "native_runtime" | "whisply_product";
