// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the report was attributable to a call that is actually running. A
 * refused report is not an error the owner should retry; the call it named has
 * already ended or never belonged to this connection.
 */
export type WhisplyToolProgressReportResponse = { published: boolean, };
