// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A native owner reporting that an admitted call it is still running has
 * reached a describable step.
 *
 * This is a report, not an authority: the app-server accepts it only for a
 * call that is in flight right now under this exact connection, thread, turn,
 * and admission, and it can never start, extend, or complete a call. A native
 * tool that takes minutes would otherwise be a silent gap in the thread.
 */
export type WhisplyToolProgressReportParams = { admissionID: string, threadID: string, turnID: string, executionID: string, label: string, fraction: number | null,
/**
 * The icon of the capability doing the work, as its descriptor names it.
 */
iconID?: string, };
