// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed trusted lease phases. Unknown values fail deserialization rather
 * than becoming an execution permission.
 */
export type WhisplyToolLeasePhase = "prepare" | "execute" | "verify" | "commit" | "resume";
