// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyBrowserSamplingPurpose } from "./WhisplyBrowserSamplingPurpose";

/**
 * Browser-only model material. No task, account, lease or native command
 * authority can be supplied through this payload.
 */
export type WhisplyBrowserSamplingPayload = { purpose: WhisplyBrowserSamplingPurpose, modelID: string, maximumOutputTokens: number, reasoningEffort: string | null, systemPrompt: string, inputJSON: string, outputSchemaJSON: string, visualJPEGDataURL: string | null, };
