// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Worker header proved this turn is using extra Exam Usage reserved for the
 * session. The thread and turn are required so the notice cannot be drawn
 * into another conversation.
 */
export type WhisplyExamExtraUsageNotification = { threadID: string, turnID: string, };
