// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyCompactionLimitScope } from "./WhisplyCompactionLimitScope";

/**
 * How close a conversation is to being shortened.
 */
export type WhisplyCompactionBudget = { contextWindowTokens: bigint | null, autoCompactLimitTokens: bigint | null, limitScope: WhisplyCompactionLimitScope, activeContextTokens: bigint, scopeTokens: bigint, tokensRemaining: bigint | null, thresholdReached: boolean,
/**
 * How much of the budget is spent, in hundredths of a percent, or absent
 * when nothing bounds the conversation.
 */
usedBasisPoints: number | null, };
