// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyModelCatalogModel } from "./WhisplyModelCatalogModel";

export type WhisplyModelCatalogReadResponse = { schemaVersion: number, catalogRevision: string, generatedAtUnixSeconds: bigint, expiresAtUnixSeconds: bigint, models: Array<WhisplyModelCatalogModel>, };
