// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyToolLeasePhase } from "./WhisplyToolLeasePhase";

/**
 * Trusted data that is never embedded in model-visible tool arguments.
 */
export type WhisplyExecutionEnvelope = { accountEpoch: string, serverIntentGrantID: string | null, taskID: string | null, taskVersion: bigint | null, leaseToken: string | null, leasePhase: WhisplyToolLeasePhase | null, deviceID: string, installationID: string, threadID: string, turnID: string, activityID: string, confirmationHash: string | null, originDigest: string | null, contentDigest: string | null, skillRunID: string | null, expiresAtMS: bigint, nonce: string, };
