// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyBrowserSampleReceipt } from "./WhisplyBrowserSampleReceipt";

export type WhisplyBrowserSampleResponse = { requestId: string, componentId: string, modelId: string, outputJSON: string, receipt: WhisplyBrowserSampleReceipt, };
