// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which mechanism shortened a conversation.
 */
export type WhisplyCompactionMechanism = "summarized" | "window_reset";
