// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Releases an activated one-turn native admission after its turn reaches a
 * terminal state. Every field is an opaque runtime correlation; this request
 * deliberately carries no execution envelope, account, target, file grant,
 * or native permission.
 */
export type WhisplyToolAdmissionFinishParams = { admissionID: string, threadID: string, turnID: string, clientUserMessageID: string, };
