// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tokens count against the automatic-shortening limit.
 */
export type WhisplyCompactionLimitScope = "total" | "body_after_prefix";
