// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyExecutionEnvelope } from "./WhisplyExecutionEnvelope";
import type { WhisplyToolModelCall } from "./WhisplyToolModelCall";
import type { WhisplyToolPolicyInput } from "./WhisplyToolPolicyInput";

/**
 * Trusted server-to-native execution request for `whisply/tool/execute`.
 */
export type WhisplyToolAppServerExecuteRequest = { call: WhisplyToolModelCall, envelope: WhisplyExecutionEnvelope, policyInputs: WhisplyToolPolicyInput, };
