// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reads the layered prompt-composition record for a thread's most recent turn.
 */
export type WhisplyPromptCompositionReadParams = { threadId: string, };
