// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyModelCatalogAvailability } from "./WhisplyModelCatalogAvailability";
import type { WhisplyModelCatalogCapabilities } from "./WhisplyModelCatalogCapabilities";
import type { WhisplyModelCatalogSubscriptionAvailability } from "./WhisplyModelCatalogSubscriptionAvailability";

export type WhisplyModelCatalogModel = { id: string, displayName: string, shortName: string, description: string, providerFamily: string, routeRevision: string, capabilities: WhisplyModelCatalogCapabilities, allowedProfiles: Array<string>, allowedReasoningEfforts: Array<string>, availability: WhisplyModelCatalogAvailability, subscriptionAvailability: WhisplyModelCatalogSubscriptionAvailability, rateCardRevision: string, usageMultiplierMillis: number, recommendedDefault: boolean, responseStartTimeoutSeconds: bigint, responseIdleTimeoutSeconds: bigint, };
