// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges that the opaque admission was accepted for one future turn.
 */
export type WhisplyToolAdmissionRegisterResponse = { accepted: boolean, };
