// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyToolPolicyDecision } from "./WhisplyToolPolicyDecision";

/**
 * Per-owner policy inputs for exactly one execution.
 */
export type WhisplyToolPolicyInput = { upstreamSandboxDecision: WhisplyToolPolicyDecision, subscriptionDecision: WhisplyToolPolicyDecision, connectorDecision: WhisplyToolPolicyDecision, nativePermissionDecision: WhisplyToolPolicyDecision, targetOrFileDecision: WhisplyToolPolicyDecision, modeDecision: WhisplyToolPolicyDecision, serverDecision: WhisplyToolPolicyDecision, finalConfirmationDecision: WhisplyToolPolicyDecision, };
