// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisplyModelCatalogCapabilities = { inputModalities: Array<string>, outputModalities: Array<string>, supportsToolCalls: boolean, supportsImages: boolean, supportsStructuredOutput: boolean, supportsSafeReasoningSummary: boolean, supportsComputerUse: boolean, supportsNativeVisibleProgress: boolean, contextLimit: bigint, outputLimit: bigint, };
