// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress delivered through the normal typed item/event path.
 *
 * The thread and turn are part of the notification because user-visible
 * activity has to be attributable: an execution id alone cannot say which
 * conversation a line belongs in, and treating it as routing authority would
 * let one thread's progress be drawn into another.
 */
export type WhisplyToolProgress = { threadID: string, turnID: string, executionID: string, label: string, fraction: number | null,
/**
 * Which capability this line is about, as the tool registry names its
 * icon. A surface that draws activity has only the execution id
 * otherwise, so every capability ends up behind one generic glyph.
 */
iconID?: string, };
