// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyPromptLayerDigest } from "./WhisplyPromptLayerDigest";
import type { WhisplyPromptProfile } from "./WhisplyPromptProfile";

export type WhisplyPromptCompositionReadResponse = { contractVersion: number, profile: WhisplyPromptProfile, modeId: string | null, layers: Array<WhisplyPromptLayerDigest>, };
