// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reads the signed customer model catalog used by the Whisply native UI.
 * Unlike `model/list`, this carries the complete verified presentation and
 * capability projection needed by the native selector.
 */
export type WhisplyModelCatalogReadParams = Record<string, never>;
