// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyBrowserSamplingPayload } from "./WhisplyBrowserSamplingPayload";

/**
 * The reference is resolved through the existing native broker for this
 * runtime process. A matching digest is required before model sampling.
 */
export type WhisplyBrowserSampleParams = { reference: string, payload: WhisplyBrowserSamplingPayload, };
