// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Registers a short-lived, owner-approved native capability set for exactly
 * one subsequent user message. The app-server binds this opaque record to
 * the connection, thread, and client message before it can reach Core.
 *
 * This does not contain an execution envelope, account identity, target,
 * confirmation, browser tab, file grant, or lease. Those remain retained by
 * the native owner and are constructed only after an admitted model call.
 */
export type WhisplyToolAdmissionRegisterParams = { admissionID: string, threadID: string, clientUserMessageID: string, toolIDs: Array<string>, };
