// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisplyToolModelCall } from "./WhisplyToolModelCall";

/**
 * A model call that matched a native owner's prior one-turn admission.
 *
 * The server targets this request to the exact registering client. The
 * receiving owner must resolve `admission_id` against its retained
 * user-approved state before it uses the existing trusted envelope bridge.
 */
export type WhisplyToolAdmittedExecuteRequest = { admissionID: string, call: WhisplyToolModelCall, threadID: string, turnID: string, clientUserMessageID: string, };
