// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cancels an in-flight model call associated with one native admission.
 */
export type WhisplyToolAdmittedCancelRequest = { executionID: string, admissionID: string, threadID: string, turnID: string, clientUserMessageID: string, };
