// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Model-visible first-party tool call. Authority data is deliberately absent.
 */
export type WhisplyToolModelCall = { executionID: string, toolID: string, schemaVersion: number, arguments: JsonValue, };
